ddfgroup/Areas/Admin/Pages/Automobile/Details.cshtml.cs
using ddfgroup.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace ddfgroup.Areas.Admin.Pages.Automobile
{
    public class DetailsModel : PageModel
    {
        private readonly ddfgroup.Data.ApplicationDbContext _context;

        public DetailsModel(ddfgroup.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public Cars Cars { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Cars = await _context.Cars
                .Include(c => c.Brands)
                .Include(c => c.CarStatus)
                .Include(c => c.Transmissions).FirstOrDefaultAsync(m => m.Id == id);

            if (Cars == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

ddfgroup/Areas/Admin/Pages/Brand/Details.cshtml.cs
using ddfgroup.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace ddfgroup.Areas.Admin.Pages.Brand
{
    public class DetailsModel : PageModel
    {
        private readonly ddfgroup.Data.ApplicationDbContext _context;

        public DetailsModel(ddfgroup.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public Brands Brands { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Brands = await _context.Brands.FirstOrDefaultAsync(m => m.BrandsId == id);

            if (Brands == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

ddfgroup/Areas/Admin/Pages/Comments/Details.cshtml.cs
using ddfgroup.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace ddfgroup.Areas.Admin.Pages.Comments
{
    public class DetailsModel : PageModel
    {
        private readonly ddfgroup.Data.ApplicationDbContext _context;

        public DetailsModel(ddfgroup.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public Feedback Feedback { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Feedback = await _context.Feedback.FirstOrDefaultAsync(m => m.Id == id);

            if (Feedback == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

ddfgroup/Areas/Admin/Pages/Content/Details.cshtml.cs
using ddfgroup.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace ddfgroup.Areas.Admin.Pages.Content
{
    public class DetailsModel : PageModel
    {
        private readonly ddfgroup.Data.ApplicationDbContext _context;

        public DetailsModel(ddfgroup.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public PageContents PageContents { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            PageContents = await _context.PageInfo.FirstOrDefaultAsync(m => m.Id == id);

            if (PageContents == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

ddfgroup/Areas/Admin/Pages/Contents/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ddfgroup.Data;

namespace ddfgroup.Areas.Contents
{
   
    public class DetailsModel : PageModel
    {
        private readonly ddfgroup.Data.ApplicationDbContext _context;

        public DetailsModel(ddfgroup.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public PageContents PageContents { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            PageContents = await _context.PageInfo.FirstOrDefaultAsync(m => m.Id == id);

            if (PageContents == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

ddfgroup/Areas/Admin/Pages/Feedback/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ddfgroup.Data;

namespace ddfgroup.Areas.Admin
{
    public class DeleteModel : PageModel
    {
        private readonly ddfgroup.Data.ApplicationDbContext _context;

        public DeleteModel(ddfgroup.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Feedback Feedback { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Feedback = await _context.Feedback.FirstOrDefaultAsync(m => m.Id == id);

            if (Feedback == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Feedback = await _context.Feedback.FindAsync(id);

            if (Feedback != null)
            {
                _context.Feedback.Remove(Feedback);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

ddfgroup/Areas/Admin/Pages/Feedback/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ddfgroup.Data;

namespace ddfgroup.Areas.Admin
{
    public class DetailsModel : PageModel
    {
        private readonly ddfgroup.Data.ApplicationDbContext _context;

        public DetailsModel(ddfgroup.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public Feedback Feedback { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Feedback = await _context.Feedback.FirstOrDefaultAsync(m => m.Id == id);

            if (Feedback == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

ddfgroup/Areas/Admin/Pages/Feedback/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ddfgroup.Data;

namespace ddfgroup.Areas.Admin
{
    public class IndexModel : PageModel
    {
        private readonly ddfgroup.Data.ApplicationDbContext _context;

        public IndexModel(ddfgroup.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IList<Feedback> Feedback { get;set; }

        public async Task OnGetAsync()
        {
            Feedback = await _context.Feedback.ToListAsync();
        }
    }
}

ddfgroup/Areas/Admin/Pages/Status/Details.cshtml.cs
using ddfgroup.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace ddfgroup.Areas.Admin.Pages.Status
{
    public class DetailsModel : PageModel
    {
        private readonly ddfgroup.Data.ApplicationDbContext _context;

        public DetailsModel(ddfgroup.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public CarStatus CarStatus { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            CarStatus = await _context.CarStatus.FirstOrDefaultAsync(m => m.CarStatusId == id);

            if (CarStatus == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

ddfgroup/Areas/Admin/Pages/TransmissionTypes/Details.cshtml.cs
using ddfgroup.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace ddfgroup.Areas.Admin.Pages.TransmissionTypes
{
    public class DetailsModel : PageModel
    {
        private readonly ddfgroup.Data.ApplicationDbContext _context;

        public DetailsModel(ddfgroup.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public Transmission Transmission { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Transmission = await _context.Transmissions.FirstOrDefaultAsync(m => m.TransmissionId == id);

            if (Transmission == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

ddfgroup/Pages/About.cshtml.cs
using ddfgroup.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace ddfgroup.Pages
{
    public class AboutModel : PageModel
    {
        private readonly ddfgroup.Data.ApplicationDbContext _context;

        public AboutModel(ddfgroup.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public PageContents PageContents { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            PageContents = await _context.PageInfo.FirstOrDefaultAsync(m => m.Id == id);
            ViewData["Content"] = PageContents.PageContent;

            if (PageContents == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

ddfgroup/Pages/Contact.cshtml.cs
using ddfgroup.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace ddfgroup.Pages
{
    public class ContactModel : PageModel
    {
        public readonly ApplicationDbContext _Context;

        public ContactModel(ApplicationDbContext context)
        {
            _Context = context;
        }

        public PageContents PageContents { get; set; }
        public async Task<IActionResult> OnGet(int? Id)
        {
            if (Id == null)
            {
                return NotFound();

            }

            PageContents = await _Context.PageInfo.FindAsync(Id);
            ViewData["Content"] = PageContents.PageContent;
            if (PageContents == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

ddfgroup/Pages/Details.cshtml.cs
using ddfgroup.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System;
using System.Threading.Tasks;
using System.Linq;
using System.Collections;

namespace ddfgroup.Pages
{
    public class DetailsModel : PageModel
    {
        public ApplicationDbContext _Context;

        public Cars Cars { get; set; }
        public IEnumerable Images { get; set; }
        public PageContents Payment { get; set; }
        private protected int Interger { get; set; } = 5;
        public string Content { get; set; }
        private string Details { get; set; } = "Details";
        private string Naira { get; set; } = "Naira";
        private Int64 Price { get; set; }
        private Currency Currency { get; set; }
      

        public DetailsModel(ApplicationDbContext Context)
        {
            _Context = Context;
        }
        public async Task<IActionResult> OnGetDetailsAsync(int cid, string handler)
        {

            Cars = await _Context.Cars
                 .Include(option => option.Brands)
                 .Include(option => option.Transmissions).FirstOrDefaultAsync(m => m.Id == cid);

              Images = _Context.CarImages.Where(a=>a.CarsId == cid);

            ViewData["Details"] = Cars.OtherDetails;
            Payment = await _Context.PageInfo.FirstOrDefaultAsync(m => m.Id == Interger);
            ViewData["Content"] = Payment.PageContent;
            return Page();

        }

        private bool CarExist(int id)
        {
            var Car = _Context.Cars.Find(id);
            if (Car != null)
            {
                return true;
            }
            else
                return false;
        }
    }
}

ddfgroup/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace ddfgroup.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ddfgroup/Pages/Naira.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Threading.Tasks;
using ddfgroup.Data;
using System.Linq;
using System.Collections;

namespace ddfgroup.Pages
{
    public class NairaModel : PageModel
    {
     
        public ApplicationDbContext _Context;
        public Cars Cars { get; set; }
        public IEnumerable Images { get; set; }
        public PageContents Payment { get; set; }
        private protected int Interger { get; set; } = 6;
        //public string Content { get; set; }
        private string Details { get; set; } = "Details";
        private string Naira { get; set; } = "Naira";
        private Int64 Price { get; set; }
        private Currency Currency { get; set; }

        public NairaModel(ApplicationDbContext Context)
        {
            _Context = Context;
        }
        public async Task<IActionResult> OnGetNairaAsync(int cid, string handler)
        {

            Cars = await _Context.Cars
                 .Include(option => option.Brands)
                 .Include(option => option.Transmissions).FirstOrDefaultAsync(m => m.Id == cid);

            Images = _Context.CarImages.Where(a => a.CarsId == cid);
            ViewData["Details"] = Cars.OtherDetails;
            Payment = await _Context.PageInfo.FirstOrDefaultAsync(m => m.Id == Interger);
            ViewData["Content"] = Payment.PageContent;
            
               //var PriceInNaira = FindCurr().Result.BaseAmount * FindCurr().Result.ExchnageRateAmount;
             

            if (Cars == null)
            {
                return NotFound();
            }
            return Page();
        }


        private bool CarExist(int cid)
        {
            var Car = _Context.Cars.Find(cid);
            if (Car != null)
            {
                return true;
            }
            else
                return false;
        }
        private async Task<Currency> FindCurr()
        {
            return await _Context.Currencies.FirstOrDefaultAsync(c => c.BaseCurrency == "USD");

        }
        private async Task<Cars> CarPrice(int cid)
        {

            var result = await _Context.Cars.FirstOrDefaultAsync(c => c.Id == cid);
            //if(result==null)
            //{
            //    return NotFound();
            //}

            return result;
        }

        public int Calculate(int BaseAmount, int ExchangeRate)
        {
            
            return BaseAmount * ExchangeRate;

        }
    }
}

ddfgroup/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace ddfgroup.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ddfgroup/Pages/About.cshtml
@page
@model ddfgroup.Pages.AboutModel

@{
    ViewData["Title"] = "About";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-12 col-lg-12 col-sm-12 colxl-12; align-content-lg-center ">
            <br/><br/>
            <h1 class="text-xxl-center">About DDf Group</h1>
            <hr />
            <dl class="row">

                <dd class="col-sm-10">

                  
                    @Html.Raw(ViewBag.Content))



                </dd>
            </dl>
        </div>
    </div>
</div>

ddfgroup/Pages/Contact.cshtml
@page
@model ddfgroup.Pages.ContactModel
@{
    Layout="~/Pages/Shared/_Layout.cshtml";
    ViewData["Title"]="Contact us";
}

<div class="container">
    <div class="row">
        <div class="col-md-12 col-lg-12 col-sm-12 colxl-12; align-content-lg-center ">
            <br /><br />
            <h1 class="text-xxl-center">@ViewData["Title"]</h1>
            <hr />
            <dl class="row">

                <dd class="col-sm-10">


                    @Html.Raw(ViewBag.Content))



                </dd>
            </dl>
        </div>
    </div>
</div>

ddfgroup/Pages/Details.cshtml
@page
@model ddfgroup.Pages.DetailsModel
@{
    var thumb = Model.Cars.ThumbFolderName;


    ViewData["Title"] = "Car Informatiopn";
    // var folder = "~/upload/wwwroot/upload/";

}

<div class="sliderinner___container"></div>

<div class="container" style="background-color:#EFEFEF; padding:15px;">
    <div class="row">
        <div class="col-sm-12 col-lg-8 col-xl-8 col-md-8">

            <div class="car___details__Container">

                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        @{
                            int count = 0;
                            string ActiveClass ="";
                            foreach (var img in Model.Images)
                            {
                                if (count == 0) { ActiveClass = "active"; }
                                <li data-target="#carouselExampleIndicators" data-slide-to="@count" class="@ActiveClass"></li>
                                count++;
                            }

                            }
                            </ol>
                    <div class="carousel-inner">
                        @{ 
                            int counter = 0;
                            var CssClass = "carousel-item active";
                            foreach (CarImages img in Model.Images)
                            { 
                                if (counter == 0) { CssClass = "carousel-item active"; } else { CssClass = "carousel-item"; }

                        <div class="@CssClass" >
                            <img class="d-block w-100" src="~/upload/@Html.DisplayFor(model => model.Cars.ThumbFolderName)/thumbs/@img.ImagesName" alt="First slide">
                        </div>
                                counter++;
                            }

                            }
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

            </div>

            @*<div class="car___details__Container">
            <input type="hidden"  value=""/>
            <img src="~/upload/@Html.DisplayFor(model => model.Cars.ThumbFolderName)/thumbs/@Html.DisplayFor(model => model.Cars.ArrayFileName)" class="rounded mx-auto d-block" />
        </div>*@


            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col"></th>
                        <th scope="col"></th>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">@Html.DisplayName("Brand") : @Html.DisplayFor(model => model.Cars.Brands.Name)</th>
                        <td>@Html.DisplayName("Model") : @Html.DisplayFor(model => model.Cars.ModelName)</td>
                        <td></td>
                        <td></td>
                    </tr>

                    <tr>
                        <th scope="row">@Html.DisplayName("Year") : @Html.DisplayFor(model => model.Cars.Year)</th>
                        <td>@Html.DisplayName("Price") : @Html.DisplayFor(model => model.Cars.Price)</td>
                        <td></td>
                        <td></td>
                    </tr>

                    <tr>
                        <th scope="row">@Html.DisplayName("Transmission") : @Html.DisplayFor(model => model.Cars.Transmissions.Name)</th>
                        <td>@Html.DisplayName("Title") : @Html.DisplayFor(model => model.Cars.CarTitle)</td>
                        <td></td>
                        <td></td>
                    </tr>

                    <tr>
                        <th scope="row">@Html.DisplayName("Mileage") : @Html.DisplayFor(model => model.Cars.Mileage)</th>
                        <td>@Html.DisplayName("Cylinder") : @Html.DisplayFor(model => model.Cars.Cylinder)</td>
                        <td></td>
                        <td></td>
                    </tr>

                    <tr>
                        <th scope="row">@Html.DisplayName("Doors") : @Html.DisplayFor(model => model.Cars.Doors)</th>
                        <td>@Html.DisplayName("Exterior Color") : @Html.DisplayFor(model => model.Cars.ExteriorColor)</td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <th scope="row">@Html.DisplayName("Exterior Color") : @Html.DisplayFor(model => model.Cars.ExteriorColor)</th>
                        <td>@Html.DisplayName("Date Uploaded") : @Html.DisplayFor(model => model.Cars.UploadedDate)</td>
                        <td></td>
                        <td></td>
                    </tr>
            </table>
            @Html.Raw(ViewBag.Details)
        </div>
    
        <div class="col-sm-12 col-md-4 col-xl-4 col-lg-4 car__container__pricing">
            <h2> Price: @Html.DisplayFor(model => model.Cars.Price)</h2>

               @Html.Raw(ViewBag.Content)
        <div class="Social-media">
            <img src="~/images/facebook.png" />
            <img src="~/images/twitter.jpg" />
            <img src="~/images/instagram.jpg" />
            <img src="~/images/watsapp.png" />
        </div>
        </div>
    </div>
    </div>

ddfgroup/Pages/Index.cshtml
@page
@model IndexModel

@{
    ViewData["Title"] = "Home";
}

<div class="slider___container">

    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="~/images/01-mercedes-benz-c-class-2018-w-205-world-premiere-3400x1440.jpg" alt="First slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="~/images/ddf-group_in_ICT-article.jpg" alt="Second slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="~/images/476204193-project-cargo.jpg" alt="Third slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

</div>
@*end slider container@*@
<div class="clearfix"></div>
@*start auto filter*@
<div class="container" id="filter__container__dark">
    <h2 class="filter-top-margin">Search for cars</h2>
    <form>
        <input type='hidden' name='__RequestVerificationToken' value='@Html.AntiForgeryToken()'>
        <div class="row filter-top-bottom-margin">
            <div class="col-lg-4 col-md-4">
                <select asp-for="Brands" class="custom-select my-1 mr-sm-12 brand-select" id="inlineFormCustomSelectPref" asp-items="ViewBag.Brands">
                    <option selected>Choose  Car Make...</option>
                </select>
            </div>
            <div class="col-lg-4 col-md-4">
                <select class="custom-select my-1 mr-sm-12 carsmodel" id="inlineFormCustomSelectPref">
                    <option selected>Choose Model</option>

                </select>
            </div>

            <div class="col">
                <button class="btn btn-danger" type="submit">Search</button>
            </div>
        </div>
    </form>
</div>
@*end cauto filter*@

<div class="container">


    <div class="row heads-padding">
        <h2 class="align-content-lg-start">SUVs &  Cars for You at DDFGroup Texas office. We also ship cars to Nigeria</h2>
        <h6>Check out these SUVs near Carrollton, TX that could be your perfect match.</h6>
    </div>
      

    <div class="row">
        @{
//int[] array = new int[] { Model.CarList};
        }
        @foreach (var mycars in Model.CarList)
        {
            var str = mycars.Price;
            //;

            <div class="col-12 col-md-6 col-lg-3 col-sm-12 col-xl-3 car__items">
                <img src="~/upload/@Html.DisplayFor(items => mycars.FolderName)/@Html.DisplayFor(items => mycars.DisplayFileName)" />
                <h1 class="car__title"> @Html.DisplayFor(items => mycars.ModelName)  -  <span class="price_color">(@mycars.Price) </span></h1>
                <h2> <span><a asp-page = "/Details" asp-page-handler="Details" asp-route-cid="@mycars.Id"> Pay in USD</a> </span> <span class="float-right"><a asp-page ="/Naira" asp-page-handler="Naira" asp-route-cid="@mycars.Id">Pay in Naira</a></span></h2>

            </div>
        }
        </div>
     
</div>

<div class="container-fluid ds-content">
    <div class="container">
        
        @Html.Raw(ViewBag.data)
        

        <div class="ds-vin"><a href="#" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">CHECK VIN NUMBER! DONT BE A VICTIM</a></div>
    </div>
</div>

<div class="int__container">

    <div class="row no-gutters">
        <div class=" col-12 col-sm-12 col-lg-6 col-md-12 col-xl-6 bez-bidge"> <img src="~/images/2018-Mercedes-Benz-C-Class-Cabriolet-Interior.jpg" /></div>
        <div class=" col-12 col-sm-12 col-lg-6 col-md-12 col-xl-6 display-4"> We consistently help you to buy good and relaibe cars. With just a few clicks, you can own your dream car.</div>
    </div>
</div>